In [1]:
import numpy as np
import numpy.linalg as la
import os

msg = "The {} product of {} and {} is {}."
vector1 = np.array([1, 0, 0])
vector2 = vector1

print(msg.format('dot', vector1, vector2, np.dot(vector1, vector2)))

The dot product of [1 0 0] and [1 0 0] is 1.


In [2]:
vector1 = np.array([1, 0, 0])
vector2 = np.array([0, 1, 0])
print(msg.format('dot', vector1, vector2, np.dot(vector1, vector2)))

The dot product of [1 0 0] and [0 1 0] is 0.


In [3]:
vector1 = np.array([2, 4, 6])
vector2 = np.array([1, 1, 1])
print(msg.format('dot', vector1, vector2, np.dot(vector1, vector2)))

The dot product of [2 4 6] and [1 1 1] is 12.


In [4]:
vector1 = np.array([1, 0, 0])
vector2 = vector1
print(msg.format('dot', vector1, vector2, np.dot(vector1, vector2)))

The dot product of [1 0 0] and [1 0 0] is 1.


In [5]:
vector1 = np.array([1, 0, 0])
vector2 = np.array([0, 1, 0])
print(msg.format('cross', vector1, vector2, np.cross(vector1, vector2)))

The cross product of [1 0 0] and [0 1 0] is [0 0 1].


In [6]:
vector1 = np.array([2, 4, 6])
vector2 = np.array([1, 1, 1])
print(msg.format('cross', vector1, vector2, np.cross(vector1, vector2)))

The cross product of [2 4 6] and [1 1 1] is [-2  4 -2].


In [7]:
print ("Solving system of linear equations (Ax = b)")
A = np.array([[ 1, -1,  0,  0,  0],
              [-1,  2, -2,  0,  0],
              [ 0, -2,  2, -2,  0],
              [ 0,  0, -2,  2, -2],
              [ 0,  0,  0, -2,  2]])
b = np.array([1, 1, 1, 1, 1])
x = la.solve(A, b)

msg = "The solution of\n {} {} = {}\n is {}"
print(msg.format(A, "[x1, x1, x3, x4, x5]", b, x))

Solving system of linear equations (Ax = b)
The solution of
 [[ 1 -1  0  0  0]
 [-1  2 -2  0  0]
 [ 0 -2  2 -2  0]
 [ 0  0 -2  2 -2]
 [ 0  0  0 -2  2]] [x1, x1, x3, x4, x5] = [1 1 1 1 1]
 is [ 1.  -0.  -1.  -1.5 -1. ]


In [12]:
lam, v = la.eig(A)

print("Determining the eigen values (A - lambda*I)*v = 0")
print("The eigen values of\n", A, "\nare", lam)
print("\nThe corresponding eigen vectors are\n", v)
print("\nQuick Test:\n", "(A*v = lambda*v):\n", np.dot(A, v[:, 0]), "=\n", lam[0] * v[:, 0])

Determining the eigen values (A - lambda*I)*v = 0
The eigen values of
 [[ 1 -1  0  0  0]
 [-1  2 -2  0  0]
 [ 0 -2  2 -2  0]
 [ 0  0 -2  2 -2]
 [ 0  0  0 -2  2]] 
are [-1.30419756  0.24599833  1.39419206  5.270692    3.39331517]

The corresponding eigen vectors are
 [[ 0.17995803 -0.63787995 -0.69897478  0.09269383 -0.25212376]
 [ 0.41465886 -0.48096255  0.27553031 -0.39586681  0.60341162]
 [ 0.59507838 -0.10286458  0.43294661  0.60103229 -0.2943094 ]
 [ 0.5684694   0.39075022 -0.14438906 -0.58702894 -0.39837874]
 [ 0.34408923  0.44555285 -0.47668263  0.35896314  0.57184297]]

Quick Test:
 (A*v = lambda*v):
 [-0.23470083 -0.54079707 -0.77609977 -0.74139641 -0.44876034] =
 [-0.23470083 -0.54079707 -0.77609977 -0.74139641 -0.44876034]
